name: CI

on:
  push:
    branches:
      - '*'
      - '!master' # Запуск CI при push  в ветки отличные от main

jobs:
  build:
    runs-on: ubuntu-latest # Запуск на последней версии Ubuntu
    steps:
      - uses: actions/checkout@v4 # Клонирование репозитория
      - name: Set up JDK 17# Установка JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Версия Java
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven # Сборка проекта с помощью Maven
        run: mvn clean install # Команда сборки
      - name: Run Tests # Запуск тестов
        run: mvn test # Команда запуска тестов